# Generated by Django 3.2 on 2022-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='配送员姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '配送员',
                'verbose_name_plural': '配送员',
                'db_table': 'df_deliver',
            },
        ),
    ]
