# Generated by Django 3.2 on 2022-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderinfo_sp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='deliver_status',
            field=models.SmallIntegerField(choices=[(1, '未送达'), (2, '已送达')], default=1, verbose_name='配送状态'),
        ),
    ]
