# Generated by Django 3.2 on 2022-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderinfo_deliver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='sp3',
            field=models.CharField(max_length=11, null=True, verbose_name='准时率'),
        ),
    ]
